[tool.poetry]
name = "br2-vision-based-smoothing"
version = "0.2.1"
description = "Video tracking and strain reconstruction algorithm for soft-arm project."
authors = ["Seung Hyun Kim <skim449@illinois.edu>"]
license = "MIT"
readme = "README.md"
packages = [
    { include = "script" },
    { include = "br2_vision" },
]

[tool.poetry.scripts]
undistort_rotate_video = 'script.undistort_rotate_video:undistort_and_rotate'
extract_frames_from_video = 'script.extract_frames_from_video:extract_frames'
trim_video_intervals_by_led = 'script.trim_video_intervals_by_led:process'
select_calibration_points = 'script.run_select_calibration_points:select_calibration_points'

distortion_calibration = 'script.distortion_calibration:calibrate'
undistort_rotate_frames = 'script.undistort_rotate_frames:undistort_and_rotate_frames'

[tool.poetry.dependencies]
python = "^3.9,<3.11"
pytest = "^7.4.0"
pyelastica = "^0.3.1.post1"
opencv-python = "^4.8.0.76"
tqdm = "^4.66.1"
scikit-learn = "^1.3.0"
scikit-spatial = "^7.0.0"
scipy = "^1.11.2"
pyqt5 = "^5.15.9"
matplotlib = "^3.7.2"
click = "^8.1.7"
psutil = "^5.9.6"

[tool.poetry.group.dev.dependencies]
pytest = "^7.4.0"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
